# The URL the site will be built for
base_url = "https://no92.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "hermit_zola"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]

home_subtitle = ""

hermit_menu = [
    { link = "/posts", name = "Posts" }
]

hermit_social = [
    { name = "github", link = "https://github.com/no92" },
    { name = "email", link = "mailto:leo@managarm.org" }
]

[extra.highlightjs]
enable = true
clipboard = true
theme = "vs2015"

[extra.author]
name = "no92"
email = "leo@managarm.org"
