on:
  push:
    branches:
      - master

name: Build and deploy to GitHub Pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
